### ISSUE TITLE
Include additional log files in `bpm logs`

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/bpm-release#22]
Is there a way, or could we add a way, for any additional log files created by running processes to be included in the `bpm logs` output?

**Comment by aramprice** [comment]
@drnic we considered this initially but opted not to because of the complexity of avoiding rotated `.gz` files, as well as not knowing whether there are nested log directories which would need to be `tail`'ed.

I'm curious if it would be worth having an implementation that might miss some logs[1] as opposed to having a the limited implementation we have now which only gets `stdout` and/or `stderr

While it won't address this issue there is a logging story coming up which would force release authors to log into a subdirectory of `/var/vcap/sys/log/<job>/` so that we can prevent the job-process from having write access to `<process>.{out|err}.log`. Link https://www.pivotaltracker.com/story/show/151341885

[1] Because we are avoiding archived logs, or because of unexpected subdirectories.

**Comment by drnic** [comment]
Ok. I'll wait until we have more `bpm` users and see if any one else get surprised when their job logs aren't in `bpm logs`. For now, I'll continue with my clipboard short cut `tail -f /var/vcap/sys/log/{*.log,*/*.log}`
