### ISSUE TITLE
Support of post-start script in bpm

### ISSUE THREAD

**Issue by karampok** [cloudfoundry-incubator/bpm-release#77]
Hi,
if we reboot manually a vm, can bpm on the restart execute the post-start?

This will allow us to solve this CFCR [issue](https://github.com/cloudfoundry-incubator/kubo-release/issues/230)

Thanks!

**Comment by xoebus** [comment]
Adding a pre-start to BPM has made a lot of people very angry and been widely regarded as a bad move. I'm a little wary to add a post-start too. It'd be neat if BOSH could change the hooks such that they will run on VM reboot.

/cc @jfmyers9

**Comment by jfmyers9** [comment]
The largest concern that I have with the `pre-start`/`post-start` in `bpm` is that they are still constrained by `monit` timeouts which is not clear. I don't think it's on any BOSH roadmap to update the `pre-start`/`post-start` to run on reboot.

Knowing these risks, it is something that we could implement if still desired, but I think I would discourage users from taking advantage of it.

**Comment by xoebus** [comment]
> I would discourage users from taking advantage of it.

Agreed.

I'm sorry: I don't think this is a path we want to keep going down. It would be nice to have these hooks run by BOSH on machine reboot. It's been a constant source of pain and bugs for years.

/cc @mfine30

**Comment by mfine30** [comment]
@xoebus or @dpb587-pivotal do you have any more insight into specific use cases or pain points? 

Danny, do you know if we have any bosh issues related to this that we could track this issue on?

**Comment by xoebus** [comment]
The concrete one which springs to mind is the Diego certificate filesystem which needs to be done in the `bpm` pre-start because it needs to be mounted on machine reboot. I don't have issues/story links handy but Perm, Garden, and MySQL have had similar requirements and ended up with the same subtle bugs. The `bpm` pre-start feature was added in order to make this easier to reason about for job authors but has since just become a source of confusion. Users can pick from either:

* Run before your job is started always with a 20 second timeout.
* Run once when new code is deployed with no timeout.

The timeouts are particularly painful because they're often not hit in development and test environments but when production data scale is used then they:

1. Blast though their timeouts.
2. Monit thinks the job has failed and tries to restart it. (The pre-start program sometimes ends up not being re-entrant and ends up (hopefully) crashing or blindly retrying and making things worse.)
4. Someone ends up getting paged.

It just feels like a particularly hostile model to reliably try and program for. The trade-offs, limitations, guarantees, and non-functional requirements aren't easy to explain. If we can work together to make this better in some way then let me know because I'd love to remove this source of bugs.

**Comment by jfmyers9** [comment]
The biggest issue with `pre-start` and `post-start` is that they do not run on VM reboot. 

Ideally users want to be able to perform unbounded critical process setup in `pre-start` / `post-start`. However, if these hooks do not execute on VM reboot, their is a good chance that their process will be unable to start after the machine is restarted. This problem is exacerbated by the fact that some infrastructures (i.e. vSphere) experience reboots more often, and it is a poor operational experience to have processes be unhealthy in the case of an unexpected reboot. This results in `pre-start` / `post-start` being useless as unbounded hooks before process execution.

Initially, I was a fan of `bpm` being able to provide these hooks as a consistent interface on every process start. This has become an issue as `bpm`'s execution is limited by the `monit` timeouts. 

If we could dream up a solution in which BOSH provides an interface that users can rely on (at least for reboot, but also on every process start), that would solve a large majority of this pain.
